# Generated by Django 3.1.4 on 2020-12-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_auto_20201206_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationexpire',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='locationexpire',
            unique_together=set(),
        ),
    ]
